import argparse
import json
import os
import sys
from pathlib import Path

sys.path.insert(0, os.path.abspath("."))

from src.concept_sets.io_utils import load_concept_vocab


ANIMAL_TERMS = {
    "horse",
    "deer",
    "zebra",
    "giraffe",
    "cat",
    "dog",
    "rabbit",
    "lion",
    "tiger",
    "wolf",
    "fox",
    "bear",
    "elephant",
    "camel",
    "cow",
    "sheep",
    "goat",
    "pig",
    "donkey",
    "pony",
    "monkey",
    "gorilla",
    "chimpanzee",
    "panda",
    "koala",
    "kangaroo",
    "otter",
    "beaver",
    "squirrel",
    "mouse",
    "rat",
    "hamster",
    "hedgehog",
    "raccoon",
    "skunk",
    "badger",
    "weasel",
    "mole",
    "bat",
    "sloth",
    "leopard",
    "cheetah",
    "jaguar",
    "panther",
    "hyena",
    "buffalo",
    "bison",
    "moose",
    "elk",
    "antelope",
    "gazelle",
    "rhino",
    "hippo",
    "boar",
    "llama",
    "alpaca",
    "yak",
    "reindeer",
    "walrus",
    "seal",
    "sea lion",
    "dolphin",
    "whale",
    "shark",
    "ray",
    "octopus",
    "squid",
    "jellyfish",
    "starfish",
    "crab",
    "lobster",
    "shrimp",
    "seahorse",
    "turtle",
    "tortoise",
    "crocodile",
    "alligator",
    "frog",
    "toad",
    "salamander",
    "lizard",
    "gecko",
    "iguana",
    "chameleon",
    "snake",
    "cobra",
    "python",
    "viper",
    "eagle",
    "hawk",
    "falcon",
    "owl",
    "sparrow",
    "robin",
    "pigeon",
    "dove",
    "parrot",
    "macaw",
    "canary",
    "penguin",
    "flamingo",
    "peacock",
    "swan",
    "goose",
    "duck",
    "chicken",
    "rooster",
    "turkey",
    "ostrich",
    "kiwi",
    "woodpecker",
    "crow",
    "raven",
    "magpie",
    "heron",
    "pelican",
    "stork",
    "butterfly",
    "moth",
    "bee",
    "wasp",
    "ant",
    "beetle",
    "ladybug",
    "dragonfly",
    "grasshopper",
    "cricket",
    "spider",
    "scorpion",
    "snail",
    "slug",
    "earthworm",
    "fish",
    "teddy bear",
}

VEHICLE_TERMS = {
    "car",
    "truck",
    "bus",
    "van",
    "taxi",
    "ambulance",
    "fire truck",
    "police car",
    "bicycle",
    "motorcycle",
    "scooter",
    "skateboard",
    "roller skates",
    "train",
    "tram",
    "subway",
    "locomotive",
    "airplane",
    "helicopter",
    "glider",
    "rocket",
    "spaceship",
    "satellite",
    "boat",
    "ship",
    "ferry",
    "submarine",
    "canoe",
    "kayak",
    "yacht",
    "sailboat",
    "jet ski",
    "tractor",
    "bulldozer",
    "excavator",
    "crane",
    "forklift",
    "wheelbarrow",
    "stroller",
    "wheelchair",
}

BUILDING_TERMS = {
    "lighthouse",
    "castle",
    "palace",
    "temple",
    "church",
    "mosque",
    "synagogue",
    "cathedral",
    "chapel",
    "monastery",
    "pagoda",
    "shrine",
    "tower",
    "skyscraper",
    "cottage",
    "cabin",
    "barn",
    "farmhouse",
    "mansion",
    "villa",
    "hut",
    "igloo",
    "tent",
    "yurt",
    "teepee",
    "greenhouse",
    "garage",
    "warehouse",
    "factory",
    "mill",
    "school",
    "library",
    "museum",
    "theater",
    "cinema",
    "stadium",
    "arena",
    "gymnasium",
    "hospital",
    "clinic",
    "hotel",
    "restaurant",
    "cafe",
    "bakery",
    "supermarket",
    "bookstore",
    "market",
    "bank",
    "post office",
    "courthouse",
    "prison",
    "airport",
    "station",
}

STRUCTURE_TERMS = {
    "bridge",
    "tunnel",
    "road",
    "highway",
    "street",
    "alley",
    "pier",
    "harbor",
    "port",
    "dam",
    "windmill",
    "watermill",
    "fountain",
    "statue",
    "monument",
    "arch",
    "gate",
    "fence",
    "wall",
    "stairs",
    "elevator",
    "escalator",
    "balcony",
    "window",
    "door",
    "chimney",
    "roof",
}

HOME_OBJECT_TERMS = {
    "sofa",
    "couch",
    "armchair",
    "chair",
    "stool",
    "bench",
    "table",
    "desk",
    "bed",
    "crib",
    "wardrobe",
    "dresser",
    "bookshelf",
    "cabinet",
    "drawer",
    "mirror",
    "lamp",
    "chandelier",
    "fan",
    "heater",
    "radiator",
    "fireplace",
    "television",
    "radio",
    "speaker",
    "microphone",
    "camera",
    "tripod",
    "projector",
    "computer",
    "laptop",
    "tablet",
    "smartphone",
    "keyboard",
    "computer mouse",
    "printer",
    "scanner",
    "headphones",
    "watch",
    "clock",
    "backpack",
    "suitcase",
    "wallet",
    "purse",
    "umbrella",
    "glasses",
    "binoculars",
    "telescope",
    "compass",
    "map",
    "notebook",
    "book",
    "magazine",
    "newspaper",
    "poster",
    "painting",
    "bust",
    "vase",
    "bottle",
    "cup",
    "mug",
    "glass",
    "plate",
    "bowl",
    "spoon",
    "fork",
    "knife",
    "chopsticks",
    "teapot",
    "kettle",
    "pot",
    "pan",
    "refrigerator",
    "microwave",
    "oven",
    "toaster",
    "blender",
    "mixer",
    "sink",
    "bathtub",
    "shower",
    "toilet",
    "soap",
    "toothbrush",
    "toothpaste",
    "towel",
    "blanket",
    "pillow",
    "carpet",
    "curtain",
    "basket",
    "bucket",
    "broom",
    "mop",
    "vacuum",
    "hammer",
    "screwdriver",
    "wrench",
    "drill",
    "saw",
    "axe",
    "shovel",
    "rake",
    "hoe",
    "ladder",
    "rope",
    "chain",
    "lock",
    "key",
    "candle",
    "lantern",
    "flashlight",
    "battery",
}

MUSIC_TERMS = {
    "guitar",
    "piano",
    "violin",
    "cello",
    "drum",
    "trumpet",
    "saxophone",
    "flute",
    "harp",
    "banjo",
    "ukulele",
    "accordion",
}

APPAREL_TERMS = {
    "helmet",
    "hat",
    "cap",
    "scarf",
    "glove",
    "boot",
    "shoe",
    "sandal",
    "sock",
    "jacket",
    "coat",
    "sweater",
    "shirt",
    "dress",
    "skirt",
    "pants",
    "jeans",
    "belt",
    "ring",
    "necklace",
    "bracelet",
    "earring",
    "crown",
}

FOOD_TERMS = {
    "apple",
    "banana",
    "orange",
    "lemon",
    "lime",
    "grape",
    "peach",
    "pear",
    "plum",
    "cherry",
    "strawberry",
    "blueberry",
    "raspberry",
    "watermelon",
    "melon",
    "pineapple",
    "mango",
    "coconut",
    "avocado",
    "tomato",
    "carrot",
    "potato",
    "onion",
    "garlic",
    "pepper",
    "broccoli",
    "cabbage",
    "lettuce",
    "spinach",
    "pumpkin",
    "corn",
    "eggplant",
    "cucumber",
    "mushroom",
    "bread",
    "cake",
    "cookie",
    "pizza",
    "burger",
    "sandwich",
    "pasta",
    "noodles",
    "rice",
    "soup",
    "salad",
    "cheese",
    "egg",
    "sausage",
}

NATURE_TERMS = {
    "mountain",
    "hill",
    "volcano",
    "cliff",
    "valley",
    "canyon",
    "desert",
    "dune",
    "forest",
    "jungle",
    "tree",
    "bush",
    "flower",
    "rose",
    "tulip",
    "sunflower",
    "daisy",
    "orchid",
    "lotus",
    "cactus",
    "fern",
    "mushroom cap",
    "grass",
    "leaf",
    "branch",
    "vine",
    "river",
    "stream",
    "waterfall",
    "lake",
    "pond",
    "ocean",
    "sea",
    "island",
    "beach",
    "glacier",
    "iceberg",
    "cloud",
    "rainbow",
    "moon",
    "sun",
    "planet",
    "star",
    "comet",
    "asteroid",
    "snowman",
}

SYNONYM_SEEDS = {
    "horse": ["stallion", "mare", "equine", "pony"],
    "cat": ["kitten", "feline", "tomcat"],
    "dog": ["puppy", "canine", "hound"],
    "jellyfish": ["medusa", "sea jelly"],
    "rabbit": ["bunny", "hare"],
    "car": ["automobile", "vehicle"],
    "truck": ["lorry"],
    "airplane": ["plane", "aircraft", "jet"],
    "bicycle": ["bike", "cycle"],
    "motorcycle": ["motorbike", "bike"],
    "ship": ["vessel"],
    "boat": ["vessel"],
    "tower": ["turret"],
    "statue": ["sculpture"],
    "waterfall": ["falls", "cascade"],
    "sea": ["ocean"],
    "flower": ["blossom", "bloom"],
    "tree": ["sapling"],
}


def assign_group(concept: str) -> str:
    if concept in ANIMAL_TERMS:
        return "animal"
    if concept in VEHICLE_TERMS:
        return "vehicle_transport"
    if concept in BUILDING_TERMS:
        return "building_place"
    if concept in STRUCTURE_TERMS:
        return "infrastructure_structure"
    if concept in HOME_OBJECT_TERMS:
        return "object_tool_household"
    if concept in MUSIC_TERMS:
        return "music_instrument"
    if concept in APPAREL_TERMS:
        return "apparel_accessory"
    if concept in FOOD_TERMS:
        return "food"
    if concept in NATURE_TERMS:
        return "nature_scene"
    return "other"


def build_synonyms(vocab: list[str]) -> dict[str, list[str]]:
    result = {}
    for concept in vocab:
        syns = SYNONYM_SEEDS.get(concept, [])
        if syns:
            # Keep deterministic order while removing dups.
            unique = []
            seen = set()
            for s in syns:
                if s not in seen:
                    seen.add(s)
                    unique.append(s)
            result[concept] = unique
    return result


def build_groups(vocab: list[str]) -> dict[str, str]:
    return {concept: assign_group(concept) for concept in vocab}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate concept synonym/group metadata JSON files.")
    parser.add_argument("--concept_vocab_path", type=str, required=True)
    parser.add_argument("--synonyms_output_path", type=str, required=True)
    parser.add_argument("--groups_output_path", type=str, required=True)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    vocab = load_concept_vocab(args.concept_vocab_path)
    synonyms = build_synonyms(vocab)
    groups = build_groups(vocab)

    syn_path = Path(args.synonyms_output_path)
    grp_path = Path(args.groups_output_path)
    syn_path.parent.mkdir(parents=True, exist_ok=True)
    grp_path.parent.mkdir(parents=True, exist_ok=True)

    with open(syn_path, "w", encoding="utf-8") as f:
        json.dump(synonyms, f, indent=2, ensure_ascii=True)
    with open(grp_path, "w", encoding="utf-8") as f:
        json.dump(groups, f, indent=2, ensure_ascii=True)

    print(f"Saved synonyms JSON: {syn_path} (targets with entries: {len(synonyms)})")
    print(f"Saved groups JSON:   {grp_path} (concepts: {len(groups)})")


if __name__ == "__main__":
    main()

